### ISSUE TITLE
Exception thrown directly after double click to download

### ISSUE THREAD

**Issue by nieuwoudtza** [Valyreon/Subloader#15]
Application: SubLoad.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException: Response status code does not indicate success: 301 (Moved Permanently).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SuppliersLibrary.OpenSubtitles.OSItem.Download(String savePath)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by nieuwoudtza** [comment]
Issue not present on v1.4.0

**Comment by Valyreon** [comment]
It could have been a temporary issue with the Opensubtitles endpoint.
